swagger: "2.0"
info:
  description: "This is a Locking resources service."
  version: "1.0.0"
  title: "Swagger Lock service"
  termsOfService: "https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html"
  contact:
    email: "zzfima@gmail.com"
host: "localhost:3004"
basePath: "/"
x-config-validation-key: "true"
paths:
  /GetVersion:
    get:
      tags:
        - "GetVersion"
      summary: "Get version of Locking service"
      description: "Get version of Locking service"
      operationId: "GetVersion"  
      produces:
        - application/json   
      responses:
        200:
          description: "Succesefully got version of Locking service"
          schema:
            type: "string"
            example: 1.1.1
        500:
          description: "Can not get version of Locking service"
          schema:
            type: string
            example: Version not found
      x-swagger-router-controller: "LockerController"
  /TryResourceLock:
    post:
      tags:
        - "TryResourceLock"
      summary: "Try lock resource by ID"
      description: "Try lock resource by ID"
      operationId: "TryResourceLock"  
      produces:
        - application/json   
      parameters:
      - in: "formData"
        name: "resourceID"
        description: "ID of rersource which try to lock"
        type: string
        required: true
      responses:
        200:
          description: "Succesefully got lock resource by ID"
          schema:
            type: object
            example: "TBD"
            properties:
              tokenID:
                type: "string"
                example: 32321321-4234234-8989989
        500:
          description: "Can not get lock resource by ID"
          schema:
            type: "string"
            example: Failed
      x-swagger-router-controller: "LockerController"